spring.application.name=assignment

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.security.jwt.secret-key=${JWT_SECRET}
spring.security.expiration-time=${JWT_EXPIRATION_TIME}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true